// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKKT5OSNIWvgHP8U0yf_Iv27xtqGu-AA',
    appId: '1:351452605170:web:fcfd67f980d36ebd3abe6b',
    messagingSenderId: '351452605170',
    projectId: 'tezda-d9ca8',
    authDomain: 'tezda-d9ca8.firebaseapp.com',
    storageBucket: 'tezda-d9ca8.firebasestorage.app',
    measurementId: 'G-XJYEW9X1MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVScUBcfNedQTNR3g5i4jfkdWEW1sWxxo',
    appId: '1:351452605170:android:bf56ef46238b33603abe6b',
    messagingSenderId: '351452605170',
    projectId: 'tezda-d9ca8',
    storageBucket: 'tezda-d9ca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSwOsxm7R8MALlEkAu06Ep25saI_leppk',
    appId: '1:351452605170:ios:cbb8af58c09336903abe6b',
    messagingSenderId: '351452605170',
    projectId: 'tezda-d9ca8',
    storageBucket: 'tezda-d9ca8.firebasestorage.app',
    iosBundleId: 'com.example.productListTezda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSwOsxm7R8MALlEkAu06Ep25saI_leppk',
    appId: '1:351452605170:ios:cbb8af58c09336903abe6b',
    messagingSenderId: '351452605170',
    projectId: 'tezda-d9ca8',
    storageBucket: 'tezda-d9ca8.firebasestorage.app',
    iosBundleId: 'com.example.productListTezda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTKKT5OSNIWvgHP8U0yf_Iv27xtqGu-AA',
    appId: '1:351452605170:web:7bc654f3786b6fe03abe6b',
    messagingSenderId: '351452605170',
    projectId: 'tezda-d9ca8',
    authDomain: 'tezda-d9ca8.firebaseapp.com',
    storageBucket: 'tezda-d9ca8.firebasestorage.app',
    measurementId: 'G-HQR9BZVJM1',
  );
}
